<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>isam-client</AssemblyName>
    <RootNamespace>IsamClient</RootNamespace>
    <LangVersion>latest</LangVersion>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Nullable>disable</Nullable>
    <OutputPath>bin\Release\</OutputPath>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="stubs\**" />
    <None Remove="stubs\**" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="BepInEx.Unity.IL2CPP" Version="6.0.0-be.788" />
    <PackageReference Include="HarmonyX" Version="2.16.1" />
    <PackageReference Include="Il2CppInterop.Runtime" Version="1.5.3" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="UnityEngine.CoreModule">
      <HintPath>lib\UnityEngine.CoreModule.dll</HintPath>
      <Private>false</Private>
    </Reference>
    <Reference Include="Assembly-CSharp">
      <HintPath>lib\Assembly-CSharp.dll</HintPath>
      <Private>false</Private>
    </Reference>
  </ItemGroup>

  <Target Name="CopyToRelease" AfterTargets="Build">
    <Copy SourceFiles="$(OutputPath)isam-client.dll"
          DestinationFolder="$(ProjectDir)release"
          SkipUnchangedFiles="true" />
  </Target>

</Project>
